adding General Bayesian Tests
jasp-stats/jaspSummaryStatistics pull request #32
Opened 2021-07-07 10:28 UTC by FBartos

analysis that allows specifying different prior distributions for a parameter and test between using different data likelihoods

(the `componentList` qml interface for the priors might not be properly updating the analysis currently - the values need to be ''verified'' with enter right, the issue is being fixed within: https://github.com/jasp-stats/jasp-test-release/issues/1360)

2021-09-24 12:19 UTC, Kucharssim requested changes
The code looks ok, I left some minor comments.

However, the analysis does not run for me, specifically it just throws unexpected error upon opening it and no amount of fiddling with the options changes that. Once you fix that, I will try it again.

rename to .jasp to see the error
[generalTestError.zip](https://github.com/jasp-stats/jaspSummaryStatistics/files/7225553/generalTestError.zip)

2021-09-24 12:19 UTC, Kucharssim commented on inst/help/summarystatsgeneralbayesiantests.md
> +  - Student-t with mean, standard deviation, and degrees of freedom
```suggestion
  - Student-t with location, scale, and degrees of freedom
```
I think it's more common to call these parameters that way?

2021-09-24 12:19 UTC, Kucharssim commented on inst/help/summarystatsgeneralbayesiantests.md
> +    - Priors: Add prior distribution to the posterior distribution plots.
```suggestion
  - Priors: Add prior distribution to the posterior distribution plots. 
```

2021-09-25 08:06 UTC, FBartos commented on inst/Description.qml
> +	}
This was a name we settled on with EJ at the end. Any second thoughts @EJWagenmakers ?

2021-09-26 08:07 UTC, FBartos commented
Oh, I see that there were significant updates to the package since I submitted the PR.

2021-09-26 09:04 UTC, FBartos commented
so, that should be fixed & I also change themeJasp to themeJaspRaw as suggested by Don elsewhere

2021-09-27 10:45 UTC, Kucharssim requested changes
Now it works!

I left one comment in the code review.

Some additional issues:

1) The lines in the prior and posterior plots appear unnecessarily thin. I would suggest making them thicker
![Screenshot 2021-09-27 at 12 31 30](https://user-images.githubusercontent.com/7093546/134892508-a6bb6d65-7875-4042-88cb-7028e562626f.png)

2) Would be really cool to add tables of the summary statistics of the posteriors. Not for this release of course, but I hope you'll add that at some point!

3) I am confused by the likelihood section somewhat. Intuitively, it seems to me that the analysis should take the sufficient statistics for the selected likelihood function to compute the results. This is for example the case when I select `Binomial` likelihood. However, for `Normal`, I can only input `mean` and `sd`, but not `sample size`, but you need that to evaluate the likelihood function from the summary statistics. So I am not sure what the analysis does without specifying the sample size: is it assuming you are observing a single trial with uncertainty or something? Or is `sd` actually `se` of the mean? Similarly, I think the analysis is a little bit cryptic about what it actually tests. Again, with binomial, it's clear that you test the parameter theta, but with normal, for example, it's a bit unclear that the only thing you can test is the mean, and it also does not communicate what it does with the variance parameter under each individual model.

2021-09-27 10:45 UTC, Kucharssim commented on inst/qml/SummaryStatsGeneralBayesianTests.qml
> +
```suggestion
import JASP 1.0
```

without this, the qml does not know how to use `JASP.None` to disallow inputing 0 for positive only parameters

2021-09-28 07:16 UTC, FBartos commented
1) Hmm, the figures are generated with the ```bayesplay``` package. Is there an easy way of editing the line thickness of the generated ggplots?
2) Good idea, I added an issue for this (https://github.com/jasp-stats/INTERNAL-jasp/issues/1561; not sure that it will be feasible with the package since it uses numerical integration though).
3) Agree, it's not really clear and the package documentation does not help (```?bayesplay::likelihood```). Not really sure what to do about that.

2021-09-28 10:15 UTC, vandenman commented
Looking at `bayesplay:::make_likelihood.normal`, the analysis treats the normal as a single observation. You'd have to enter the standard error yourself to get the distribution of sufficient statistics. This is probably not ideal.

2021-09-28 11:10 UTC, Kucharssim commented
> 1. Hmm, the figures are generated with the bayesplay package. Is there an easy way of editing the line thickness of the generated ggplots?

I think you could use `scale_size_manual()`, but not sure whether that will work.

> 3. Agree, it's not really clear and the package documentation does not help (?bayesplay::likelihood). Not really sure what to do about that.

> Looking at bayesplay:::make_likelihood.normal, the analysis treats the normal as a single observation. You'd have to enter the standard error yourself to get the distribution of sufficient statistics. This is probably not ideal.

Right. Yeah, according to the website, you need to put in SE manually in order it to work properly (https://bayesplay.github.io/bayesplay/articles/basic.html). I think we want to avoid the situation that people will add their standard deviation into the analysis thinking that the analysis will test the mean properly, as they would have to calculate the SE instead. Should we rename the option then? It really depends on whether you consider it as a data from a single uncertain observation (where the SD would be appropriate), or whether it's a summary statistic of many observations (in which SE would be appropriate). Also, the analysis assumes then that the variance parameter is known I think, so I guess it's good to at least communicate it clearly with a footnote or something.

2021-09-28 14:20 UTC, FBartos commented
So, the ```scale_size_manual()``` didn't work, so I had to extract the plotting functions from the package. The line thickness should be in line with the JASP theme.

And I changed the SD label to SE to make it clearer.

2021-09-28 14:37 UTC, AlexanderLyNL commented
> Looking at `bayesplay:::make_likelihood.normal`, the analysis treats the normal as a single observation. You'd have to enter the standard error yourself to get the distribution of sufficient statistics. This is probably not ideal.

Perhaps mention this to the package maintainer.

2021-09-28 14:40 UTC, FBartos commented
OK, mentioned.

2021-09-29 10:46 UTC, Kucharssim approved these changes
> I needed to extract all plotting functions from the bayesplay package for it. I guess it's gonna bite us if/when the author updates the internal functions...

Yeah, that's unfortunate. I do think that the plots look much better now though. I think the ideal scenario would be to ask the maintainer of the package to allow users to specify the width of the lines - are you in touch with them so that you can ask if that's possible? Alternatively, you can submit a feature request on their GitHub page. If that's implemented, we can revert back to using the plotting functions from the package. I also give you a bit of a leeway with the snake case that is in the functions that you copied over.

2021-09-29 10:47 UTC, merged